src/Infrastructure/Entity/Goal.php
<?php

declare(strict_types=1);

namespace App\Infrastructure\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Infrastructure\Repository\UserRepository")
 */
class Goal implements \JsonSerializable
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=36)
     */
    private string $goalIdentifier;

    /**
     * @ORM\Column(type="string")
     */
    private string $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isFinished;

    /**
     * @ORM\Column(type="text")
     */
    private string $realizationDescription;

    /**
     * @ORM\ManyToOne(targetEntity="Task", inversedBy="goals")
     * @ORM\JoinColumn(name="task_id", referencedColumnName="id")
     */
    private Task $task;

    public function setGoalIdentifier(string $goalIdentifier): Goal
    {
        $this->goalIdentifier = $goalIdentifier;

        return $this;
    }

    public function setName(string $name): Goal
    {
        $this->name = $name;

        return $this;
    }

    public function setIsFinished(bool $isFinished): Goal
    {
        $this->isFinished = $isFinished;

        return $this;
    }

    public function setRealizationDescription(string $realizationDescription): Goal
    {
        $this->realizationDescription = $realizationDescription;

        return $this;
    }

    public function setTask($task)
    {
        $this->task = $task;

        return $this;
    }

    public function jsonSerialize(): array
    {
        return [
            'goal_identifier' => $this->goalIdentifier,
            'name' => $this->name,
            'is_finished' => $this->isFinished,
            'description' => $this->realizationDescription
        ];
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getGoalIdentifier(): string
    {
        return $this->goalIdentifier;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function isFinished(): bool
    {
        return $this->isFinished;
    }

    public function getRealizationDescription(): string
    {
        return $this->realizationDescription;
    }

    public function getTask(): Task
    {
        return $this->task;
    }
}

src/Infrastructure/Entity/Task.php
<?php

declare(strict_types=1);

namespace App\Infrastructure\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Infrastructure\Repository\TaskRepository")
 */
class Task
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=36)
     */
    private string $uuid;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="createdTasks")
     * @ORM\JoinColumn(name="creator_id", referencedColumnName="id")
     */
    private User $creator;

    /**
     * @ORM\Column(type="integer")
     */
    private int $requiredWorkers;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTime $startDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTime $endDate;

    /**
     * @ORM\OneToMany(targetEntity="Goal", mappedBy="task")
     */
    private $goals;

    /**
     * @ORM\ManyToMany(targetEntity="User", inversedBy="tasks")
     * @ORM\JoinTable(name="task_user")
     */
    private $workers;

    public function __construct()
    {
        $this->goals = new ArrayCollection();
        $this->workers = new ArrayCollection();
    }

    public function setCreator($creator): Task
    {
        $this->creator = $creator;
        return $this;
    }

    public function setRequiredWorkers(int $requiredWorkers): Task
    {
        $this->requiredWorkers = $requiredWorkers;
        return $this;
    }

    public function setStartDate(DateTime $startDate): Task
    {
        $this->startDate = $startDate;
        return $this;
    }

    public function setEndDate(DateTime $endDate): Task
    {
        $this->endDate = $endDate;
        return $this;
    }

    public function setWorkers(array $workers): Task
    {
        $this->workers = $workers;
        return $this;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getCreator(): User
    {
        return $this->creator;
    }

    public function getRequiredWorkers(): int
    {
        return $this->requiredWorkers;
    }

    public function getStartDate(): DateTime
    {
        return $this->startDate;
    }

    public function getEndDate(): DateTime
    {
        return $this->endDate;
    }

    /**
     * @return Collection|User[]
     */
    public function getWorkers(): Collection
    {
        return $this->workers;
    }

    /**
     * @return Collection|Goal[]
     */
    public function getGoals(): Collection
    {
        return $this->goals;
    }

    public function addGoal(Goal $goal): Task
    {
        $this->goals[] = $goal;
        $goal->setTask($this);

        return $this;
    }

    /**
     * @param Goal[] $goals
     */
    public function setGoals(array $goals): Task
    {
        foreach ($goals as $goal) {
            $this->addGoal($goal);
        }

        return $this;
    }

    public function addWorker(User $user): Task
    {
        $this->workers[] = $user;
        $user->addTask($this);

        return $this;
    }

    public function removeWorker(User $user): Task
    {
        $this->workers->removeElement($user);
        $user->removeTask($this);

        return $this;
    }

    public function getUuid(): string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): Task
    {
        $this->uuid = $uuid;
        return $this;
    }

    public function isStarted(): bool
    {
        return $this->getStartDate() < new DateTime();
    }

    public function isFinished(): bool
    {
        return $this->getEndDate() <= new DateTime();
    }

    public function __toString(): string
    {
        return $this->uuid;
    }
}

templates/frontend/homepage.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
    a,
    a:focus,
    a:hover {
        color: #fff;
    }
    .btn-secondary,
    .btn-secondary:hover,
    .btn-secondary:focus {
        color: #333;
        text-shadow: none; /* Prevent inheritance from `body` */
        background-color: #fff;
        border: .05rem solid #fff;
    }
    html,
    body {
        height: 100%;
        background-color: #333;
    }
    body {
        display: -ms-flexbox;
        display: flex;
        color: #fff;
        text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
        box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
    }
    .cover-container {
        max-width: 42em;
    }
    .masthead {
        margin-bottom: 2rem;
    }
    .masthead-brand {
        margin-bottom: 0;
    }
    .nav-masthead .nav-link {
        padding: .25rem 0;
        font-weight: 700;
        color: rgba(255, 255, 255, .5);
        background-color: transparent;
        border-bottom: .25rem solid transparent;
    }
    .nav-masthead .nav-link:hover,
    .nav-masthead .nav-link:focus {
        border-bottom-color: rgba(255, 255, 255, .25);
    }
    .nav-masthead .nav-link + .nav-link {
        margin-left: 1rem;
    }
    .nav-masthead .active {
        color: #fff;
        border-bottom-color: #fff;
    }
    @media (min-width: 48em) {
        .masthead-brand {
            float: left;
        }
        .nav-masthead {
            float: right;
        }
    }
    .cover {
        padding: 0 1.5rem;
    }
    .cover .btn-lg {
        padding: .75rem 1.25rem;
        font-weight: 700;
    }
    .mastfoot {
        color: rgba(255, 255, 255, .5);
    }
</style>
{% endblock %}
{% block body_id %}
    class="text-center"
{% endblock %}
{% block body %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <h3 class="masthead-brand">Task Manager</h3>
                <nav class="nav nav-masthead justify-content-center">
                    <a class="nav-link" href="#">About</a>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <a class="nav-link" href="{{ path('app_logout')}}">Logout</a>
                    {% endif %}
                </nav>
            </div>
        </header>

        <main role="main" class="inner cover">
            <h1 class="cover-heading">Task manager application LIVE TEST!</h1>
            <p class="lead">Create task, manage the deadlines add new workers - easily with a joy!</p>
            <p class="lead">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <a href="{{ path('app_tasks') }}" class="btn btn-lg btn-secondary">Jump to your tasks</a>
                {% else %}
                    <a class="btn btn-lg btn-primary" href="{{ path('connect_google_start') }}">
                        Log in with google
                    </a>
                {% endif %}
            </p>
        </main>

        <footer class="mastfoot mt-auto">
            <div class="inner">
                <p>Purple Clouds 2020 - Mateusz Kozioł</p>
            </div>
        </footer>
    </div>
{% endblock %}

templates/frontend/tasks.html.twig
{% extends 'base.html.twig' %}

{% block title %} Tasks {% endblock %}
{% block stylesheets %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            min-height: 75rem;
            padding-top: 4.5rem;
        }
    </style>
{% endblock %}
{% block body %}
    {% include 'shared/navigation.html.twig' %}
    <main role="main" class="container">
        <div class="d-flex justify-content-center border-bottom mb-3">
            <div class="my-4">
                <h1>List of tasks</h1>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="card-deck">
                {% if tasks is empty %}
                    <div class="alert alert-info">
                        <lead>There're no tasks defined yet!</lead>
                    </div>
                {% else %}
                    {% for task in tasks %}
                        <div class="card">
                                {% if task.finished %}
                                    <div class="card-header bg-secondary text-white font-weight-bold">Task finished</div>
                                {% elseif task.started %}
                                    <div class="card-header bg-success text-white font-weight-bold">Task started</div>
                                {% else %}
                                    <div class="card-header bg-dark text-white font-weight-bold">Task not started</div>
                                {% endif %}
                            <div class="card-body">
                                <h5 class="card-title"><img class="img img-fluid rounded-circle" width="40px"
                                                            alt="User picture"
                                                            src="{{ task.creator.picture }}"/> {{ task.creator.name }}
                                </h5>
                                <p class="card-text">
                                    <span class="lead text-bold">Goals</span>
                                    <ul class="list-group">
                                        {% for goal in task.goals %}
                                        <li class="list-group-item">
                                            <p class="lead">{{ goal.name }}</p>
                                            <hr>
                                            <p class="text-break">
                                                {{ goal.realizationDescription }}
                                            </p>
                                            {% if goal.isFinished %}
                                                <div class="font-weight-bold text-success">✓</div>
                                            {% else %}
                                                <div class="font-weight-bold text-danger">✗</div>
                                            {% endif %}
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </p>
                                {% if task.workers is empty %}
                                    <button class="btn btn-dark js-participate-in-task" type="button"
                                            data-task-participate-url="{{ absolute_url(path('task_participate', {'taskId':task.id})) }}">
                                        Participate in task
                                    </button>
                                {% endif %}
                                {% for worker in task.workers %}
                                    {% if worker.id != app.user.id %}
                                        <button class="btn btn-dark js-participate-in-task" type="button"
                                                data-task-participate-url="{{ absolute_url(path('task_participate', {'taskId':task.id})) }}">
                                            Participate in task
                                        </button>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="card-footer">
                                <h6 class="text-muted">Start: {{ task.startDate|date('Y-m-d') }}</h6>
                                <h6 class="text-muted">End: {{ task.endDate|date('Y-m-d') }}</h6>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            let participateInTaskBtn = $(".js-participate-in-task");

            participateInTaskBtn.on('click', function () {
                let taskParticipateUrl = $(this).data('task-participate-url');

                let taskRequest = $.ajax({
                    type: 'GET',
                    url: taskParticipateUrl,
                });

                taskRequest.done(function (data) {
                    alert("You have joined a task as a worker");
                    location.reload();
                });

                taskRequest.fail(function (response) {
                    alert('Something went wrong:' + response.responseText);
                });

                return false;
            });
        });
    </script>
{% endblock %}

templates/frontend/user_tasks.html.twig
{% extends 'base.html.twig' %}

{% block title %} Tasks {% endblock %}
{% block stylesheets %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
        body {
            min-height: 75rem;
            padding-top: 4.5rem;
        }
    </style>
{% endblock %}
{% block body %}
    {% include 'shared/navigation.html.twig' %}
    <main role="main" class="container">
        <div class="d-flex justify-content-center border-bottom mb-3">
            <div class="my-4">
                <h1>List of tasks</h1>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="card-deck">
                {% if tasks is empty %}
                    <div class="alert alert-info">
                        <lead>There're no tasks defined yet!</lead>
                    </div>
                {% else %}
                    {% for task in tasks %}
                        <div class="card">
                            {% if task.finished %}
                                <div class="card-header bg-secondary text-white font-weight-bold">Task finished</div>
                            {% elseif task.started %}
                                <div class="card-header bg-success text-white font-weight-bold">Task started</div>
                            {% else %}
                                <div class="card-header bg-dark text-white font-weight-bold">Task not started</div>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title"><img class="img img-fluid rounded-circle" width="40px" alt="User picture" src="{{ task.creator.picture }}"/>  {{ task.creator.name }} </h5>
                                <p class="card-text">
                                    <span class="lead text-bold">Goals</span>
                                    <ul class="list-group">
                                    {% for goal in task.goals %}
                                        <li class="list-group-item">
                                            <span class="lead">{{ goal.name }}</span>
                                            <p class="text-break lead">
                                                {{ goal.realizationDescription }}
                                            </p>
                                            {% if goal.isFinished %}
                                                <div class="font-weight-bold text-success">✓</div>
                                            {% else %}
                                                <div class="font-weight-bold text-danger">✗</div>
                                                {% for worker in task.workers %}
                                                    {% if worker.id == app.user.id %}
                                                    <button class="badge badge-info js-goal-mark-as-done" type="button"
                                                            data-goal-mark-as-done-url="{{ absolute_url(path('goal_mark_as_done', {'uuid':goal.goalIdentifier})) }}">
                                                        mark done
                                                    </button>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                    </ul>
                                </p>
                                {% for worker in task.workers %}
                                    {% if worker.id == app.user.id %}
                                        <button class="btn btn-dark js-resign-from-task" type="button"
                                                data-task-resign-url="{{ absolute_url(path('task_resign', {'taskId':task.id})) }}">
                                            Resign
                                        </button>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="card-footer">
                                <h6 class="text-muted">Start: {{ task.startDate|date('Y-m-d') }}</h6>
                                <h6 class="text-muted">End: {{ task.endDate|date('Y-m-d') }}</h6>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            const resignFromTaskBtn = $(".js-resign-from-task");
            const goalMarkAsDoneBtn = $(".js-goal-mark-as-done");

            resignFromTaskBtn.on('click', function () {
                const taskResignUrl = $(this).data('task-resign-url');

                let r = $.ajax({
                    type: 'GET',
                    url: taskResignUrl,
                });

                r.done(function (data) {
                    alert("You have resigned from a task");
                    location.reload();
                });

                r.fail(function (response) {
                    alert('Something went wrong:' + response.responseText);
                });

                return false;
            });

            goalMarkAsDoneBtn.on('click', function () {
                const goalMarkAsDoneUrl = $(this).data('goal-mark-as-done-url');

                let r = $.ajax({
                    type: 'GET',
                    url: goalMarkAsDoneUrl,
                });

                r.done(function (data) {
                    alert("You have just marked a goal as finished! Congratulations!");
                    location.reload();
                });

                r.fail(function (response) {
                    alert('Something went wrong:' + response.responseText);
                });

                return false;
            });
        });
    </script>
{% endblock %}